### ISSUE TITLE
关于 UI 导入 psd

### ISSUE THREAD

**Issue by hqzh** [imcuttle/measure#3]
![_20180926094257](https://user-images.githubusercontent.com/26128706/46052380-c925dd80-c170-11e8-8653-d524c7707105.png)
请问下这个页面支持psd文件选择用chrome打开或拖拽进chrome进入到这个页面吗?或者本地怎么到这个导入的页面?

**Comment by imcuttle** [comment]
@hqzh   在页面的右上方有导入按钮，或者拖拽 psd 文件至页面中也可以导入

**Comment by hqzh** [comment]
@imcuttle 我的意思是这个页面是在线的,可否搞成无网络访问?

**Comment by imcuttle** [comment]
@hqzh   在 chrome 或其他类 chrome 浏览器中，下载(Cmd / Ctrl + S)页面即可

**Comment by hqzh** [comment]
用bash命令行 measure-export start 可以达到我的需求,这个命令可以自定义改短点吗?

**Comment by hqzh** [comment]
这个命令可以递归当前文件夹下所有的psd就好了(文件夹下还有文件夹下的psd,  不过现在很棒了!)

**Comment by imcuttle** [comment]
命令行的是可以递归搜索的吧
![image](https://user-images.githubusercontent.com/13509258/46063862-85e36300-c1a0-11e8-9ac9-f098698719f1.png)
![image](https://user-images.githubusercontent.com/13509258/46063945-98f63300-c1a0-11e8-9187-65b539cb0d9b.png)

```bash
measure-export start ~/Desktop/psd
```

**Comment by hqzh** [comment]
是可以,可能我文件太多太大了,有点慢,试了一下小点的可以
