### ISSUE TITLE
能否增加导出图片的功能

### ISSUE THREAD

**Issue by yushiro** [imcuttle/measure#6]
针对每个图层，自动导出png或者jpg。
目前我看到的是导出的一整张图片，对于实际工作， 好像还不太够用。

**Comment by imcuttle** [comment]
@yushiro 你好，首先感谢你的 issue，目前该项目是一个实验性质的开源项目，还有一些已知的 bug 尚未解决（如 #4 ），所以建议你目前实际使用还是类似 [pxcook](http://www.fancynode.com.cn/pxcook) 的成熟盈利项目

然后，关于你说的图层图片导出的支持，之前也有考虑过，后面之所以不将所有的图层都使用图片来表示，有如下考虑点：
1. 会大大提升资源大小，而且每个图层都会有重叠部分，所以会有很多重叠覆盖的图层，如果均设置图片导出，又会许多的冗余图片
2. 后续考虑采用 [Sketch Measure](https://github.com/utom/sketch-measure) 的方式来提供一个统一的面板来提供切图管理，如图
![image](https://user-images.githubusercontent.com/13509258/54484671-f3e22a80-48a5-11e9-8806-e3db6a77dce0.png)
